---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/v/1/session' : 'App\Web\API\SessionAPI'
    'api/v/1/signin' : 'App\Web\API\SigninAPI'
    #'api/v/1/signup' : 'App\Web\API\SignupAPI'
    'api/v/1/signout' : 'App\Web\API\SignoutAPI'
    'api/v/1/search' : 'App\Web\API\SearchAPI'
    'api/v/1/contact' : 'App\Web\API\ContactAPI'
    'api/v/1/member/$Action' : 'App\Web\API\MemberAPI'
    'password-recovery' : 'App\Web\Controller\PasswordRecoveryController'
    'api/v/1/client/$action/$id' : 'App\Web\API\ClientAPI'
    'api/v/1/project/$id/$action' : 'App\Web\API\ProjectAPI'
    'api/v/1/workflow/$id/$action' : 'App\Web\API\WorkflowAPI'
    'api/v/1/invoice/$action' : 'App\Web\API\InvoiceAPI'
    'api/v/1/userstory/$id/$action' : 'App\Web\API\UserstoryAPI'
    'projects/$slug': 'App\Web\Controller\ProjectController'
    'clients/$slug/$action': 'App\Web\Controller\ClientController'
    'invoices/$id/$action': 'App\Web\Controller\InvoiceController'
    'api/v/1/search-clients/$search': 'App\Web\API\ClientSearchAPI'
